services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
      - TERM=xterm-256color  # ターミナル出力用
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    tty: true
    depends_on:
      - db
    env_file:
      - .env
    command: tail -f /dev/null

  db:
    image: mysql:8.0
    volumes:
      - ./data/mysql:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
    ports:
      - "3306:3306"

volumes:
  tiktok_data:
